### ISSUE TITLE
add standardized JBrowse2 links to yaml for jekyll consumption

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/LIS-autocontent#1]
Currently, the jekyll sites link to JBrowse2 by just going to the main entrypoint page, befuddling some users who are more used to the traditional "when I ask to see a genome browser I get a genome" sort of approach. The JBrowse2 URL API allows links into specific assemblies, and to specify what tracks will be enabled, as well as more complex cases like pairwise comparisons between assemblies for a dotplot view. The autocontent generator could facilitate use of this in the jekyll context by constructing a specific yaml file that creates links for all the assemblies (enabling the annotation track by default if it exists), and any pairwise comparisons under the synteny folders that exist in the form of paf files. The jekyll builder could consume this yaml file and add the links to the resources page, as is currently done for older browsers in a semi-manual process (ie the yaml files are constructed manually). Can specify this more concretely if needed.

**Comment by ctcncgr** [comment]
Complete. reopen if needed.
