### ISSUE TITLE
use of assembly aliases in auto-generated jbrowse2 configs is problematic for some purposes

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/LIS-autocontent#14]
I just ran into some issues with text searching that seem to be caused by inadequate understanding by some parts of the jbrowse ecosystem of the use of reference genome aliasing (ie things specified as --alias to add-assembly).

In my case it was both:
 - the jbrowse text-index command did not recognize tracks were associated with reference genomes when they use the alias (ie the indexing of tracks would simply be skipped, unless you specified the alias explicitly as `jbrowse text-index -a arahy.Tifrunner.gnm1`
 - the jbrowse client would completely ignore indexes generated in this way
 
I think @ctcncgr has also seen some other contexts in which similar problems arise if you try to use the alias for a genome rather than the given "name". So, this may well be a jbrowse2 bug but for now I think it would be better for the config generation to use the forms like "arahy.Tifrunner.gnm1" as the name and use --displayName to set the "human readable" version. 

This looks like a simple change in way the jbrowse cli is called, I can PR it but this provides the context for why I'm proposing the change.

**Comment by ctcncgr** [comment]
Closing. Accepted PR #15 

I do believe this to be a bug in jbrowse2, but maybe it isn't. Either way this is a good solution. Thanks @adf-ncgr
