### ISSUE TITLE
bam_name not declared

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/LIS-autocontent#39]
https://github.com/legumeinfo/LIS-autocontent/commit/a083d8ff07eff2e37e39ed767a51be0616046804#diff-794aa24529bb6da3cad71d57ea1c597df5d654779414fef62732f9bc4f1a1281L186 seems to have deleted the line that declared bam_name but not the subsequent line that references that variable. I think we probably ought to just restore that line, but maybe this was going in a different direction. In any case, it currently throws an error when genome alignments are processed.

**Comment by ctcncgr** [comment]
Hey @adf-ncgr sorry about that, I thought we had tested the code when @el239 and I pushed it up. One of us will fix this. Thanks!

**Comment by el239** [comment]
@ctcncgr I've pushed that fix to the develop branch now.
