### ISSUE TITLE
BUSCO modifications

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/LIS-autocontent#6]
per updated datastore specs (see the end for BUSCO):
https://github.com/legumeinfo/datastore-specifications/blob/main/Genus/species/annotations#readme
https://github.com/legumeinfo/datastore-specifications/tree/main/Genus/species/genomes#readme

I will update the md5 files in the datastore so you can use them, and when the code is updated we can look at populating DSCensor with the now current data. 

Up to you if you want to use the genome stats encoded in the genome-BUSCO files or generate new ones using the seqtools option, let's just try to make everything consistent and complete in DSCensor (unlike in the foundations of formal mathematics)

**Comment by adf-ncgr** [comment]
md5 files on datastore should have all the BUSCO files listed now. all yours

**Comment by ctcncgr** [comment]
This should be done with the most recent PR from develop. Reopen if needed.
